/* Generated by Cython 0.28.3 */

#ifndef __PYX_HAVE__sentiment_analysis
#define __PYX_HAVE__sentiment_analysis

#ifndef __PYX_HAVE_API__sentiment_analysis

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#include <python2.7/Python.h>

__PYX_EXTERN_C std::string clean_tweet(std::string);
__PYX_EXTERN_C int get_tweet_sentiment(std::string);
__PYX_EXTERN_C std::pair<int,int>  sentiment_count(std::list<std::string>*);

#endif /* !__PYX_HAVE_API__sentiment_analysis */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
__PYX_EXTERN_C PyMODINIT_FUNC initsentiment_analysis(void);
#else
__PYX_EXTERN_C PyMODINIT_FUNC PyInit_sentiment_analysis(void);
#endif

#endif /* !__PYX_HAVE__sentiment_analysis */
